version: 2
jobs:
  build:
    working_directory: ~/wp-calypso
    docker:
      - image: 'circleci/node:$NODE_VERSION-browsers'
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-calypso && git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          keys:
            - v1-npmcache-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/npm-shrinkwrap.json" }}
            - v1-npmcache-{{ checksum "wp-calypso/.nvmrc" }}
            - v1-npmcache
      - run: cd wp-calypso/test/e2e && npm ci
      - save_cache:
          key: v1-npmcache-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/package-lock.json" }}
          paths:
            - "~/.npm"
      - run: sudo chmod +x wp-calypso/test/e2e/node_modules/.bin/mocha && sudo chmod +x wp-calypso/test/e2e/specs-jetpack/runner.sh
      - run: cd wp-calypso/test/e2e && npm run decryptconfig && ./specs-jetpack/runner.sh
      - store_test_results:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/screenshots/
